ERICA-Club-Hub/Frontend

.prettierrc, src/components/Common/TopNavigator.tsx, src/components/Common/index.ts, src/constants/navigations.ts, src/pages/admin/auth/login/AdminLoginPage.tsx
-
- TOP NAVI 공통 컴포넌트 UI 구현
<br>
-
<br>
=> [Feat] TOP NAVI 공통 컴포넌트 UI 구현

src/components/Common/TopNavigator.tsx, src/pages/admin/auth/login/AdminLoginPage.tsx, src/store/navAtom.ts
-
-
<br>
- TOP NAVI 컴포넌트 활성화 상태 전역 상태로 관리
- 활성화 UI 개선
<br>
=> [Refactor] TOP NAVI 컴포넌트 활성화 상태 전역 상태로 관리

src/components/Common/TopNavigator.tsx, src/pages/admin/auth/login/AdminLoginPage.tsx, src/store/navAtom.ts
-
<br>
- TOP NAVI 컴포넌트 활성화 상태 전역 상태로 관리
<br>
=> [Refactor] TOP NAVI 컴포넌트 활성화 로컬 상태로 관리

src/components/Common/Input.tsx, src/components/Common/index.ts, src/pages/admin/auth/login/AdminLoginPage.tsx
- #8 
<br>
- 어드민 로그인 UI 구현
- 입력 로직 구현
<br>
=> 8 admin login UI

src/pages/admin/union/main/AdminUnionPage.tsx
- #24 
- resolve: #24 
<br>
- 총동연 어드민 홈 UI 구현 
<br>
=> feat: 총동연 어드민 홈 UI 구현 

src/components/Common/Card.tsx, src/pages/notice/ServiceNoticePage.tsx, src/pages/notice/UnionNoticePage.tsx
- #33 
- resolve: #33 
<br>
- 서비스 공지사항 페이지 ui 구현
<br>
> X
=> feat: 서비스 공지사항 UI 구현  (#33)

src/components/Common/Card.tsx, src/pages/notice/UnionNoticePage.tsx
- #31 
- resolve: #31 
<br>
- 총동연 공지사항 페이지 ui 구현
<br>
> X
=> feat: 총동연 공지사항 UI 구현 (#31)

src/pages/notice/UnionNoticePage.tsx, src/pages/resources/ResourcesPage.tsx
- #34 
- resolve: #34 
<br>
- 자료실 페이지 ui 구현
<br>
> X
=> feat: 자료실 구현 (#34)

src/assets/common/expand-arrow.svg, src/components/Common/Dropdown.tsx, src/components/Common/HeaderMenu.tsx, src/components/Common/InputField.tsx, src/components/Common/RootLayout.tsx, src/components/Common/index.ts, src/pages/admin/auth/login/AdminLoginPage.tsx, src/pages/admin/auth/register/RegisterClubPage.tsx
- #11 
- resolve: #11 
<br>
<br>
=> feat: 어드민 등록 UI 구현

src/pages/admin/auth/register/RegisterClubPage.tsx, src/pages/admin/union/notice/AdminNoticePage.tsx, src/types/index.ts, src/types/input_value.ts, src/utils/imageHandler.ts, src/utils/index.ts
- #28 
- resolve: #28 
<br>
- 총동연 공지사항 등록 UI 구현
<br>
=> feat: 총동연 공지사항 등록 UI 

src/assets/common/main_next_arrow.svg, src/assets/common/main_prev_arrow.svg, src/pages/club-list/ClubListPage.tsx
- #51 
- resolve: #51
<br>
- 메인페이지 중 메인공지사항 부분 ui 구현
<br>
=> feat: 메인페이지 메인공지 구현 (#51)

src/assets/common/main_next_arrow.svg, src/assets/common/main_prev_arrow.svg, src/pages/club-list/ClubListPage.tsx
- #51 
- resolve: #51 #53 
<br>
- 메인페이지 메인 공지사항 부분 ui 구현
<br>
=> 51 union mainannouncement UI

src/components/Common/Card.tsx
- #59 
- #59 
<br>
- FAQ 페이지 card안 tag 리팩토링
<br>
=> refactor: FAQ 페이지 card안 tag 리팩토링

src/components/Common/Card.tsx
- #59 
- resolve: #59 #60 
<br>
- FAQ 페이지 card안의 tag 리팩토링
<br>
=> fefactor: FAQ 페이지 card안의 tag 리팩토링

src/hooks/useClickOutside.ts, src/pages/club-detail/ActivityLogModal.tsx, src/pages/club-detail/tab/Log.tsx
- #46 
- resolve: #46 
<br>
- 활동 로그에 올라간 사진들을 클릭했을 때 나타날 모달의 UI 디자인을 적용한 PR입니다
<br>
- 모달에 < > X 같은 아이콘이 들어가는데 html css로 작업하는게 좋을까요 아니면 svg를 사용하는게 좋을까요?
- 여유 되신다면 `git fetch origin` -> `git checkout 46-activity-log-modal-ui` 후 추가 작업 여부 간단하게 확인해주시면 감사하겠습니다!(귀찮으시면 굳이 확인 안해보셔도 돼요!)
=> 46 activity log modal UI

src/components/Common/Card.tsx, src/pages/notice/ServiceNoticePage.tsx
- #40 
- resolve: #40 
<br>
- 서비스 공지사항 page api 구현
<br>
=> feat: 서비스 공지사항 api 구현

src/components/Common/SortingDropdown.tsx, src/pages/FAQ/FAQPage.tsx, src/pages/club-list/ClubListPage.tsx
- #63 
- resolve: #63 
<br>
- 메인페이지 동아리 검색 로직 구현
<br>
=> feat: 동아리 검색 로직 구현

src/components/Common/SortingDropdown.tsx, src/pages/FAQ/FAQPage.tsx, src/pages/club-list/ClubListPage.tsx
- #63 
-resolve: #63 
<br>
- 메인페이지 동아리 검색 로직 구현
<br>
=> 63 club search logic

src/components/Common/Card.tsx, src/components/Common/SortingDropdown.tsx, src/pages/FAQ/FAQPage.tsx, src/pages/club-list/ClubListPage.tsx, src/pages/notice/ServiceNoticePage.tsx, src/pages/notice/UnionNoticePage.tsx
- #32 
- resolve: #32 
<br>
- 총동연 공지사항 페이지 로직 구현 및 api 구현
<br>
=> feat: 총동연 공지사항 로직 및 api 구현

src/pages/FAQ/FAQPage.tsx, src/pages/resources/ResourcesPage.tsx
- #75 
-resolve: #75 
<br>
- 총동연 공지사항 구현 중 빌드 오류 해결
<br>
=> fix: 총동연 공지사항 빌드 오류 해결

src/pages/club-list/ClubListPage.tsx
- #78 
- resolve: #78 
<br>
- 메인페이지 구현 중 빌드 오류 해결
<br>
=> fix: 메인페이지 빌드 오류 해결

src/App.tsx, src/components/Common/Button.tsx, src/pages/admin/union/resources/AdminResourcesRegisterPage.tsx, src/pages/index.ts, src/pages/resources/register/ResourcesRegisterPage.tsx
- #70 
- resolve: #70 
<br>
-자료실 - 자료 등록하기 UI 및 파일 업로드 기능 구현
- 작업하다보니 삭제하기 버튼은 outline의 색이 mainBlue가 아니라 따로 지정해주려면 번거롭더라구요 그래서 `<Button>` 컴포넌트에 prop로 색상 받을 수 있도록 수정하였습니다.
<br>
=> 70 resources register UI

src/components/Common/Card.tsx, src/pages/club-list/ClubListPage.tsx, src/pages/notice/UnionNoticePage.tsx
- #81 
-resolve: #81 
<br>
- 메인 페이지 총동연 메인공지 thumbnail받아오기 api 구현
- 메인 페이지 동아리 검색 (필터링 및 정렬) api 구현
<br>
=> feat: 메인 페이지 로직 및 api 구현 

src/components/Common/Card.tsx, src/pages/club-list/ClubListPage.tsx, src/pages/notice/UnionNoticePage.tsx
- #81 
-resolve: #81 
<br>
- 메인 페이지 총동연 메인공지 thumbnail받아오기 api 구현
- 메인 페이지 동아리 검색 (필터링 및 정렬) api 구현
<br>
=> feat: 메인페이지 로직 및 api 구현

src/components/Common/Card.tsx
- #94 
-resolve: #94 
<br>
- 공통 컴포넌트 Card props 리팩토링
<br>
=> refactor: 공통 컴포넌트 Card props 리팩토링 (#94)

src/components/Common/Card.tsx
- #94 
-resolve: #94 
<br>
- 공통 컴포넌트 Card props 리팩토링
<br>
=> feat: 공통 컴포넌트 Card props 리팩토링

src/api/apiRequest.ts, src/hooks/useAdminLogin.ts, src/pages/admin/auth/register/RegisterClubPage.tsx, src/pages/admin/union/notice/AdminNoticePage.tsx, src/types/club-register.types.ts, src/types/index.ts, src/types/input_value.ts, src/utils/imageHandler.ts
- #12  #13 
- #12  #13
<br>
- 어드민 동아리 등록 로직 및 API 연동
<br>
=> 어드민 동아리 등록 로직 및 API 연동

src/constants/club-detail-register.ts, src/hooks/useBulletPointConverter.ts, src/pages/admin/club/detail/RecruitNotice.tsx, src/routes/Routes.tsx, src/types/input-value.types.ts
- #102 
<br>
- 로직 구현
- API 연동
- textarea 불릿 포인터 커스텀 훅 구현
<br>
=> 동아리 어드민 상세 모집안내 API 연동

index.html, src/components/Common/HeaderMenu.tsx, src/components/Common/RootLayout.tsx, src/constants/navigations.ts, src/hooks/index.ts, src/hooks/useAdminLogin.ts, src/hooks/useAuthenticationToggle.ts, src/hooks/usefilteredHeaderMenuList.ts, src/index.css, src/store/authState.ts
- #104 
<br>
- 로그인 로그아웃 플로우 개선
- GNB 상단 고정
<br>
=> 어드민 로그인 / 로그아웃 플로우 개선

src/components/Common/Card.tsx, src/pages/FAQ/FAQPage.tsx, src/pages/notice/ServiceNoticePage.tsx, src/pages/notice/UnionNoticePage.tsx, src/pages/resources/ResourcesPage.tsx
- #111 
<br>
- 상단 메뉴 페이지들 반응형을 고려해서 가운데 정렬로 ui 수정했습니다!
<br>
=> style: 상단 메뉴 페이지 가운데 정렬 ui 수정 (#111)

src/pages/club-list/ClubListPage.tsx, src/pages/notice/ServiceNoticePage.tsx, src/pages/notice/UnionNoticePage.tsx, src/pages/resources/ResourcesPage.tsx
- #114 
<br>
- 메인페이지에서 card를 클릭했을 때, 그에 해당하는 동아리 상세페이로 이동하는 로직 구현
<br>
=> feat: 메인페이지와 동아리 상세페이지 로직 연동 (#114)

src/pages/resources/ResourcesPage.tsx
- #117 
<br>
- 자료실 다운로드 버튼 클릭 시 바로 다운로드 되도록 로직 변경
- 이전 : presigned URL 클릭 시 URL 타고 이동
- 현재 : presigned URL을 통해서 버튼 클릭 시 바로 다운로드 
<br>
=> feat: 자료실 다운로드 로직 구현 (#117)

src/pages/FAQ/FAQPage.tsx, src/pages/club-list/ClubListPage.tsx
- #87 
<br>
- 배포 환경에서 이미지가 깨지는 오류 수정
- 상대 경로를 절대 경로로 수정
<br>
=> bugfix: 이미지 렌더링 깨짐 오류 수정 (#87)

src/pages/FAQ/FAQPage.tsx, src/pages/club-list/ClubListPage.tsx, src/pages/notice/ServiceNoticePage.tsx, src/pages/resources/ResourcesPage.tsx
- #87 
<br>
- 배포환경에서 메인페이지 이미지 렌더링 수정
- 상단 메뉴 페이지들 상대경로 -> 절대 경로로 수정 (상단메뉴는 이미지 깨짐 현상이 없었으나 만약을 대비해서 절대경로로 수정해 놨습니다!)
- 백엔드 분들에게 부탁해서 4173포트 열어서 수정 완료했습니다!
<br>
=> bugfix : 메인페이지 포함 상단 페이지들 이미지 렌더링 오류 수정

src/pages/club-list/ClubListPage.tsx
- #134 
<br>
- 파일명으로 인한 빌딩 오류 해결
<br>
=> bugfix: 파일명으로 인한 빌딩 오류 해결 (#134)

src/components/AdminClubDetail/ClubIntro/ClubDescription.tsx, src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx, src/constants/navigations.ts, src/hooks/queries/useClubAdminQueries.ts, src/hooks/queries/useServiceAdminQueries.ts, src/pages/admin/club/detail/section/ClubIntroPage.tsx, src/pages/admin/club/detail/section/RecruitNoticePage.tsx, src/pages/admin/club/detail/section/SummaryInfoPage.tsx, src/pages/admin/service/AdminClubRegisterManagePage.tsx, src/pages/index.ts, src/routes/Routes.tsx, src/routes/ServiceAdminGuard.tsx
=> 서비스 어드민 동아리 등록 요청 관리 페이지 및 기능 

src/hooks/queries/useClubAdminQueries.ts, src/pages/FAQ/FAQPage.tsx
-
<br>
-
<br>
@ssxrxbx 
`FAQ` 페이지 두번 째 질문 삭제 및 첫 번째 질문 문구 수정했습니다!
확인 부탁드려용
=> 3차 merge [develop -> main]

src/components/Common/MainpageCard.tsx
- #142 
<br>
- 모바일 환경에서 메인페이지 동아리별 카드 내용 아래로 치우쳐지는 현상 해결
<br>
=> Design: 메인페이지 카드 치우쳐짐 해결

src/components/ClubRegister/ClubRegisterForm.tsx, src/hooks/queries/useClubRegisterQueries.ts, src/pages/admin/club/main/AdminClubPage.tsx
=> 동아리 등록 정보 기본 이미지 설정 제거

src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx, src/hooks/queries/useClubAdminQueries.ts, src/pages/admin/club/detail/section/ClubIntroPage.tsx
- #152 
<br>
- 동아리 상세 월별 일정 입력 및 수정 오류 해결
- 동아리 상제 월별 일정 삭제 기능 구현
=> 동아리 상세 월별 일정 입력 오류 수정 및 삭제 기능 구현

src/components/AdminClubDetail/ClubIntro/EventSchedule.tsx, src/constants/club-detail-register.ts, src/hooks/queries/useClubAdminQueries.ts, src/pages/admin/club/detail/section/ClubIntroPage.tsx, src/pages/admin/club/detail/section/SummaryInfoPage.tsx, src/types/club-detail.types.ts
- #160 
<br>
- 동아리 정보 수정란 문구 수정
- 월별 일정 삭제 로직 변경 (기존: 삭제 누를때마다 API 요청 -> 변경 : 저장 트리거시 한번에 보내기)
=> 동아리 정보 문구 수정 및 월별 일정 삭제 로직 변경

src/components/Common/Footer.tsx, src/components/Common/Modal/MainModal.tsx, src/components/Common/Modal/Modal.tsx, src/pages/club-list/ClubListPage.tsx
- #165 
<br>
- 공통 컴포넌트 Modal.tsx수정으로 인한 오류 해결
- 메인 페이지 모달을 추가로 생성 (MainModal.tsx)
- Footer 빌딩 오류 해결
<br>
=> hotfix: 공통 컴포넌트 모달 오류 해결 (#165)

src/pages/club-detail/ClubDetailPage.tsx
=> 동아리 상제 정보 요약 UI 수정 [develop -> main]

src/components/Common/HeaderMenu.tsx
=> 로고 홈 라우팅 추가

src/pages/club-detail/ClubDetailPage.tsx
=> style : fontsize 지정

src/pages/club-detail/tab/Intro.tsx
fix : 연간 일정 flex 부여 및 정렬 기준 수정
=> fix : 연간 일정 flex 부여 및 정렬 기준 수정

src/pages/club-detail/tab/Intro.tsx
=> chore : 누락된 커밋 업로드

src/api/apiRequest.ts, src/components/ActivityLog/ActivityLogForm.tsx, src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx, src/hooks/queries/useClubAdminQueries.ts
-
<br>
- 활동로그 상세, 어드민 동아리 소개 토큰 만료 시 임시로 `alert`로 핸들링
<br>
=> 활동로그 상세, 어드민 동아리 소개 토큰 만료 임시 에러 핸들링

src/components/ActivityLog/ActivityLogForm.tsx, src/components/AdminClubDetail/ClubIntro/MonthlyEventSchedule.tsx, src/hooks/queries/useClubAdminQueries.ts
- #187 
<br>
- 기존 alert로 임시 401 핸들링 -> handleError 훅으로 관리
<br>
=> 활동로그, 월별 일정 세션 만료 에러 핸들링
